apis:
  github@local:
    root: resources/pets.yaml
    lint:
      extends:
        -  resources/nested-config.yaml
      rules:
        operation-2xx-response: off

  github@url:
    root: resources/pets.yaml
    lint:
      extends:
        -  https://raw.githubusercontent.com/Redocly/openapi-cli/master/packages/core/src/config/__tests__/fixtures/resolve-remote-configs/remote-config.yaml

  github@plugin:
    root: resources/pets.yaml
    lint:
      extends:
        - recommended
        - resources/config-with-plugin.yaml
        
  github@old:
    root: resources/31.yaml
    lint: 
      extends: []
      rules: 
        operation-2xx-response: warn
        operation-400-response: error
        scalar-property-missing-example: warn
        
lint:
  rules: 
    operation-summary: warn

