apis:
  third:
    root: ./petstore-with-errors.yaml
    lint:
      rules:
        operation-2xx-response: warn

lint:

  extends:
    - recommended
  rules:
    # operation-2xx-response: '????'
    # no-invalid-media-type-examples: '????'
    operation-description: off
    # path-http-verbs-order: '????'
    # boolean-parameter-prefixes: '????'
  preprocessors:
    # local/duplicate-description: on
  decorators:
    # local/inject-x-stats: on
features.openapi:
  showConsole: true
  layout:
    scope: section
  routingStrategy: browser
  theme:
    rightPanel:
      backgroundColor: '#263238'
    links:
      color: '#6CC496'