apis:
  main:
    root: ./petstore-with-errors.yaml
    lint:
      rules:
        operation-2xx-response: error

lint:
  extends: 
    - minimal
  rules:
    operation-2xx-response: error
    no-invalid-media-type-examples: error
    operation-description: error
    path-http-verbs-order: error
    boolean-parameter-prefixes: error
  preprocessors:
    # local/duplicate-description: on
  decorators:
    # local/inject-x-stats: on
features.openapi:
  showConsole: false
  layout:
    scope: section
  routingStrategy: browser
  theme:
    rightPanel:
      backgroundColor: '#263238'
    links:
      color: '#6CC496'